import type { Metadata } from 'next';
import { Geist, Geist_Mono, Pixelify_Sans, Funnel_Display, Funnel_Sans, Host_Grotesk } from 'next/font/google';
import './globals.css';
import SiteFooter from '@/components/site-footer';
import { ThemeProvider } from 'next-themes';
import LiquidSideNav from '@/components/liquid-side-nav';
import MainLayout from '@/layouts/main-layout';
import { FloatingNav } from '@/components/ui/floating-nav';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

const pixelifySans = Pixelify_Sans({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  fallback: ['system-ui', 'sans-serif'],
  variable: '--font-pixelify-sans',
  display: 'swap',
  style: ['normal'],
});

const funnelDisplay = Funnel_Display({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  fallback: ['system-ui', 'sans-serif'],
  variable: '--font-funnel-display',
  display: 'swap',
  style: ['normal'],
});

const funnelSans = Funnel_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  fallback: ['system-ui', 'sans-serif'],
  variable: '--font-funnel-sans',
  display: 'swap',
  style: ['normal', 'italic'],
});

const hostGrotesk = Host_Grotesk({
  subsets: ['latin'],
  weight: 'variable',
  fallback: ['system-ui', 'sans-serif'],
  variable: '--font-host-grotesk',
  display: 'swap',
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pixelifySans.variable} ${funnelDisplay.variable} ${funnelSans.variable} ${hostGrotesk.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange={false}>
          <FloatingNav />
          <LiquidSideNav />
          <MainLayout>{children}</MainLayout>
          <SiteFooter />
        </ThemeProvider>
      </body>
    </html>
  );
}
